package com.sh.lynn.huang.wdaccount.been;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BANK_CARD".
 */
public class BankCard {

    /** Not-null value. */
    private String cardID;
    /** Not-null value. */
    private String cardNum;
    private String money;
    private String bankName;
    private Integer billDate;
    private Integer repaymentDate;
    private Integer cardType;

    public BankCard() {
    }

    public BankCard(String cardID, String cardNum, String money, String bankName, Integer billDate, Integer repaymentDate, Integer cardType) {
        this.cardID = cardID;
        this.cardNum = cardNum;
        this.money = money;
        this.bankName = bankName;
        this.billDate = billDate;
        this.repaymentDate = repaymentDate;
        this.cardType = cardType;
    }

    /** Not-null value. */
    public String getCardID() {
        return cardID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCardID(String cardID) {
        this.cardID = cardID;
    }

    /** Not-null value. */
    public String getCardNum() {
        return cardNum;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public Integer getBillDate() {
        return billDate;
    }

    public void setBillDate(Integer billDate) {
        this.billDate = billDate;
    }

    public Integer getRepaymentDate() {
        return repaymentDate;
    }

    public void setRepaymentDate(Integer repaymentDate) {
        this.repaymentDate = repaymentDate;
    }

    public Integer getCardType() {
        return cardType;
    }

    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

}
