package com.sh.lynn.huang.wdaccount.been;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BANK_CARD".
 */
public class BankCard {

    /** Not-null value. */
    private String cardID;
    /** Not-null value. */
    private String cardNum;
    private String balance;
    private String bankName;
    private java.util.Date billTime;
    private Integer cardType;

    public BankCard() {
    }

    public BankCard(String cardID, String cardNum, String balance, String bankName, java.util.Date billTime, Integer cardType) {
        this.cardID = cardID;
        this.cardNum = cardNum;
        this.balance = balance;
        this.bankName = bankName;
        this.billTime = billTime;
        this.cardType = cardType;
    }

    /** Not-null value. */
    public String getCardID() {
        return cardID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCardID(String cardID) {
        this.cardID = cardID;
    }

    /** Not-null value. */
    public String getCardNum() {
        return cardNum;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    public String getBalance() {
        return balance;
    }

    public void setBalance(String balance) {
        this.balance = balance;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public java.util.Date getBillTime() {
        return billTime;
    }

    public void setBillTime(java.util.Date billTime) {
        this.billTime = billTime;
    }

    public Integer getCardType() {
        return cardType;
    }

    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

}
