package com.sh.lynn.huang.wdaccount.been;

import com.sh.lynn.huang.wdaccount.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.sh.lynn.huang.wdaccount.dao.MoneyRecordDao;
import com.sh.lynn.huang.wdaccount.dao.PlatformDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MONEY_RECORD".
 */
public class MoneyRecord {

    private Long id;
    private double money;
    private java.util.Date time;
    private String cardNum;
    private long platformId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MoneyRecordDao myDao;

    private Platform platform;
    private Long platform__resolvedKey;


    public MoneyRecord() {
    }

    public MoneyRecord(Long id) {
        this.id = id;
    }

    public MoneyRecord(Long id, double money, java.util.Date time, String cardNum, long platformId) {
        this.id = id;
        this.money = money;
        this.time = time;
        this.cardNum = cardNum;
        this.platformId = platformId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMoneyRecordDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getMoney() {
        return money;
    }

    public void setMoney(double money) {
        this.money = money;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public String getCardNum() {
        return cardNum;
    }

    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    public long getPlatformId() {
        return platformId;
    }

    public void setPlatformId(long platformId) {
        this.platformId = platformId;
    }

    /** To-one relationship, resolved on first access. */
    public Platform getPlatform() {
        long __key = this.platformId;
        if (platform__resolvedKey == null || !platform__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PlatformDao targetDao = daoSession.getPlatformDao();
            Platform platformNew = targetDao.load(__key);
            synchronized (this) {
                platform = platformNew;
            	platform__resolvedKey = __key;
            }
        }
        return platform;
    }

    public void setPlatform(Platform platform) {
        if (platform == null) {
            throw new DaoException("To-one property 'platformId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.platform = platform;
            platformId = platform.getId();
            platform__resolvedKey = platformId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
