package com.sh.lynn.huang.wdaccount.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sh.lynn.huang.wdaccount.been.Platform;
import com.sh.lynn.huang.wdaccount.been.MoneyRecord;
import com.sh.lynn.huang.wdaccount.been.TenderRecord;

import com.sh.lynn.huang.wdaccount.dao.PlatformDao;
import com.sh.lynn.huang.wdaccount.dao.MoneyRecordDao;
import com.sh.lynn.huang.wdaccount.dao.TenderRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig platformDaoConfig;
    private final DaoConfig moneyRecordDaoConfig;
    private final DaoConfig tenderRecordDaoConfig;

    private final PlatformDao platformDao;
    private final MoneyRecordDao moneyRecordDao;
    private final TenderRecordDao tenderRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        platformDaoConfig = daoConfigMap.get(PlatformDao.class).clone();
        platformDaoConfig.initIdentityScope(type);

        moneyRecordDaoConfig = daoConfigMap.get(MoneyRecordDao.class).clone();
        moneyRecordDaoConfig.initIdentityScope(type);

        tenderRecordDaoConfig = daoConfigMap.get(TenderRecordDao.class).clone();
        tenderRecordDaoConfig.initIdentityScope(type);

        platformDao = new PlatformDao(platformDaoConfig, this);
        moneyRecordDao = new MoneyRecordDao(moneyRecordDaoConfig, this);
        tenderRecordDao = new TenderRecordDao(tenderRecordDaoConfig, this);

        registerDao(Platform.class, platformDao);
        registerDao(MoneyRecord.class, moneyRecordDao);
        registerDao(TenderRecord.class, tenderRecordDao);
    }
    
    public void clear() {
        platformDaoConfig.getIdentityScope().clear();
        moneyRecordDaoConfig.getIdentityScope().clear();
        tenderRecordDaoConfig.getIdentityScope().clear();
    }

    public PlatformDao getPlatformDao() {
        return platformDao;
    }

    public MoneyRecordDao getMoneyRecordDao() {
        return moneyRecordDao;
    }

    public TenderRecordDao getTenderRecordDao() {
        return tenderRecordDao;
    }

}
