package com.sh.lynn.huang.wdaccount.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.sh.lynn.huang.wdaccount.been.Platform;

import com.sh.lynn.huang.wdaccount.been.InvestRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INVEST_RECORD".
*/
public class InvestRecordDao extends AbstractDao<InvestRecord, Long> {

    public static final String TABLENAME = "INVEST_RECORD";

    /**
     * Properties of entity InvestRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Money = new Property(1, double.class, "money", false, "MONEY");
        public final static Property TenderTime = new Property(2, java.util.Date.class, "tenderTime", false, "TENDER_TIME");
        public final static Property CalInteresttype = new Property(3, Integer.class, "calInteresttype", false, "CAL_INTERESTTYPE");
        public final static Property During = new Property(4, Integer.class, "during", false, "DURING");
        public final static Property TenderType = new Property(5, String.class, "tenderType", false, "TENDER_TYPE");
        public final static Property TenderState = new Property(6, String.class, "tenderState", false, "TENDER_STATE");
        public final static Property Rate = new Property(7, Double.class, "rate", false, "RATE");
        public final static Property Desc = new Property(8, String.class, "desc", false, "DESC");
        public final static Property FundsName = new Property(9, String.class, "fundsName", false, "FUNDS_NAME");
        public final static Property FundsCode = new Property(10, String.class, "fundsCode", false, "FUNDS_CODE");
        public final static Property Funds_pf = new Property(11, String.class, "funds_pf", false, "FUNDS_PF");
        public final static Property P2p_pj_name = new Property(12, String.class, "p2p_pj_name", false, "P2P_PJ_NAME");
        public final static Property PlatformId = new Property(13, long.class, "platformId", false, "PLATFORM_ID");
    };

    private DaoSession daoSession;

    private Query<InvestRecord> platform_InvestRecordListQuery;

    public InvestRecordDao(DaoConfig config) {
        super(config);
    }
    
    public InvestRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INVEST_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MONEY\" REAL NOT NULL ," + // 1: money
                "\"TENDER_TIME\" INTEGER," + // 2: tenderTime
                "\"CAL_INTERESTTYPE\" INTEGER," + // 3: calInteresttype
                "\"DURING\" INTEGER," + // 4: during
                "\"TENDER_TYPE\" TEXT," + // 5: tenderType
                "\"TENDER_STATE\" TEXT," + // 6: tenderState
                "\"RATE\" REAL," + // 7: rate
                "\"DESC\" TEXT," + // 8: desc
                "\"FUNDS_NAME\" TEXT," + // 9: fundsName
                "\"FUNDS_CODE\" TEXT," + // 10: fundsCode
                "\"FUNDS_PF\" TEXT," + // 11: funds_pf
                "\"P2P_PJ_NAME\" TEXT," + // 12: p2p_pj_name
                "\"PLATFORM_ID\" INTEGER NOT NULL );"); // 13: platformId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INVEST_RECORD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, InvestRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getMoney());
 
        java.util.Date tenderTime = entity.getTenderTime();
        if (tenderTime != null) {
            stmt.bindLong(3, tenderTime.getTime());
        }
 
        Integer calInteresttype = entity.getCalInteresttype();
        if (calInteresttype != null) {
            stmt.bindLong(4, calInteresttype);
        }
 
        Integer during = entity.getDuring();
        if (during != null) {
            stmt.bindLong(5, during);
        }
 
        String tenderType = entity.getTenderType();
        if (tenderType != null) {
            stmt.bindString(6, tenderType);
        }
 
        String tenderState = entity.getTenderState();
        if (tenderState != null) {
            stmt.bindString(7, tenderState);
        }
 
        Double rate = entity.getRate();
        if (rate != null) {
            stmt.bindDouble(8, rate);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(9, desc);
        }
 
        String fundsName = entity.getFundsName();
        if (fundsName != null) {
            stmt.bindString(10, fundsName);
        }
 
        String fundsCode = entity.getFundsCode();
        if (fundsCode != null) {
            stmt.bindString(11, fundsCode);
        }
 
        String funds_pf = entity.getFunds_pf();
        if (funds_pf != null) {
            stmt.bindString(12, funds_pf);
        }
 
        String p2p_pj_name = entity.getP2p_pj_name();
        if (p2p_pj_name != null) {
            stmt.bindString(13, p2p_pj_name);
        }
        stmt.bindLong(14, entity.getPlatformId());
    }

    @Override
    protected void attachEntity(InvestRecord entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public InvestRecord readEntity(Cursor cursor, int offset) {
        InvestRecord entity = new InvestRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getDouble(offset + 1), // money
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // tenderTime
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // calInteresttype
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // during
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // tenderType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tenderState
            cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7), // rate
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // desc
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // fundsName
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // fundsCode
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // funds_pf
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // p2p_pj_name
            cursor.getLong(offset + 13) // platformId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, InvestRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMoney(cursor.getDouble(offset + 1));
        entity.setTenderTime(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setCalInteresttype(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setDuring(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setTenderType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTenderState(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setRate(cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7));
        entity.setDesc(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFundsName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setFundsCode(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFunds_pf(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setP2p_pj_name(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPlatformId(cursor.getLong(offset + 13));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(InvestRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(InvestRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "investRecordList" to-many relationship of Platform. */
    public List<InvestRecord> _queryPlatform_InvestRecordList(long platformId) {
        synchronized (this) {
            if (platform_InvestRecordListQuery == null) {
                QueryBuilder<InvestRecord> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PlatformId.eq(null));
                platform_InvestRecordListQuery = queryBuilder.build();
            }
        }
        Query<InvestRecord> query = platform_InvestRecordListQuery.forCurrentThread();
        query.setParameter(0, platformId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPlatformDao().getAllColumns());
            builder.append(" FROM INVEST_RECORD T");
            builder.append(" LEFT JOIN PLATFORM T0 ON T.\"PLATFORM_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected InvestRecord loadCurrentDeep(Cursor cursor, boolean lock) {
        InvestRecord entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Platform platform = loadCurrentOther(daoSession.getPlatformDao(), cursor, offset);
         if(platform != null) {
            entity.setPlatform(platform);
        }

        return entity;    
    }

    public InvestRecord loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<InvestRecord> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<InvestRecord> list = new ArrayList<InvestRecord>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<InvestRecord> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<InvestRecord> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
