package com.sh.lynn.huang.wdaccount.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.sh.lynn.huang.wdaccount.been.Platform;

import com.sh.lynn.huang.wdaccount.been.MoneyRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MONEY_RECORD".
*/
public class MoneyRecordDao extends AbstractDao<MoneyRecord, Long> {

    public static final String TABLENAME = "MONEY_RECORD";

    /**
     * Properties of entity MoneyRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Money = new Property(1, double.class, "money", false, "MONEY");
        public final static Property Time = new Property(2, java.util.Date.class, "time", false, "TIME");
        public final static Property CardNum = new Property(3, String.class, "cardNum", false, "CARD_NUM");
        public final static Property PlatformId = new Property(4, long.class, "platformId", false, "PLATFORM_ID");
    };

    private DaoSession daoSession;

    private Query<MoneyRecord> platform_MoneyRecordListQuery;

    public MoneyRecordDao(DaoConfig config) {
        super(config);
    }
    
    public MoneyRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MONEY_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MONEY\" REAL NOT NULL ," + // 1: money
                "\"TIME\" INTEGER," + // 2: time
                "\"CARD_NUM\" TEXT," + // 3: cardNum
                "\"PLATFORM_ID\" INTEGER NOT NULL );"); // 4: platformId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MONEY_RECORD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MoneyRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getMoney());
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(3, time.getTime());
        }
 
        String cardNum = entity.getCardNum();
        if (cardNum != null) {
            stmt.bindString(4, cardNum);
        }
        stmt.bindLong(5, entity.getPlatformId());
    }

    @Override
    protected void attachEntity(MoneyRecord entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MoneyRecord readEntity(Cursor cursor, int offset) {
        MoneyRecord entity = new MoneyRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getDouble(offset + 1), // money
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // cardNum
            cursor.getLong(offset + 4) // platformId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MoneyRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMoney(cursor.getDouble(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setCardNum(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPlatformId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MoneyRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MoneyRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "moneyRecordList" to-many relationship of Platform. */
    public List<MoneyRecord> _queryPlatform_MoneyRecordList(long platformId) {
        synchronized (this) {
            if (platform_MoneyRecordListQuery == null) {
                QueryBuilder<MoneyRecord> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PlatformId.eq(null));
                platform_MoneyRecordListQuery = queryBuilder.build();
            }
        }
        Query<MoneyRecord> query = platform_MoneyRecordListQuery.forCurrentThread();
        query.setParameter(0, platformId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPlatformDao().getAllColumns());
            builder.append(" FROM MONEY_RECORD T");
            builder.append(" LEFT JOIN PLATFORM T0 ON T.\"PLATFORM_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MoneyRecord loadCurrentDeep(Cursor cursor, boolean lock) {
        MoneyRecord entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Platform platform = loadCurrentOther(daoSession.getPlatformDao(), cursor, offset);
         if(platform != null) {
            entity.setPlatform(platform);
        }

        return entity;    
    }

    public MoneyRecord loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MoneyRecord> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MoneyRecord> list = new ArrayList<MoneyRecord>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MoneyRecord> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MoneyRecord> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
